/** @format */
import React from 'react';
import '../styles/globals.css';
import { Poppins } from 'next/font/google';
import Ga4 from '@/utils/ga4.component';
import Script from 'next/script';
import Header from '@/components/header';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
	title: "🚀 tem's recs",
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<Script type='text/javascript' id='clarity'>
					{`
          (function (c, l, a, r, i, t, y) {
    c[a] = c[a] || function () { (c[a].q = c[a].q || []).push(arguments); };
    t = l.createElement(r); t.async = 1; t.src = "https://www.clarity.ms/tag/" + i;
    y = l.getElementsByTagName(r)[0]; y.parentNode.insertBefore(t, y);
})(window, document, "clarity", "script", "i2n3gilivs");
          `}
				</Script>
			</head>
			<body className={poppins.className}>
				<Ga4>
					<div
						className='w-full border-b-2 dark:border-bgAccentLight border-bgAccentDark 
						h-52 sticky top-0'
					>
						<Header />
					</div>
					<div className='h-screen dark:bg-bgAccentDark bg-bgAccentLight'>
						{children}
					</div>
				</Ga4>
			</body>
		</html>
	);
}
